youtubeClientRedirectUrl: http://localhost
hiMessages:
  neydora: Seid gegrüßt, gnädige Quallenkönigin!
  35xy9om_uranus:
    - Na ihr Swiffer, was cruncht?
    - Na ihr Sniffer, was schnanscht?
    - Naan ayya fof wif fif fif flolf föf wääw cruaurc saas
youtubeDlPath: youtube-dl
youtubeDlCookieFile: /home/jaid/youtubeDlCookies.txt
youtubeDlFormat: bestvideo[ext=webm]+bestaudio[ext=webm]/bestvideo+bestaudio/best
dotaSteamId32: "90387906"
dotaPollIntervalSeconds: 60
travisPollIntervalSeconds: 30
youtubeSubscriptionsPollIntervalSeconds: 300
observedYoutubeChannels:
  - name: Daily Dose
    id: UCdC0An4ZPNr_YiFiYoVbwaw
twitterFollowedIds:
  - name: Jaidchen
    id: "1910506442"
  - name: Twitch
    id: "437210567"
categoryShortcuts:
  dbd: Dead by Daylight
  chat: Just Chatting
starredReleasesPollIntervalSeconds: 3600
starredReleasesUser: Jaid
watchedSteamDepotIds:
  - name: Dota 2 (Windows x64)
    id: "373303"
  - name: Dead by Daylight
    id: "381211"
watchSteamGamesIntervalSeconds: 300
twitchClientCallbackUrl: http://localhost:17441/auth/twitch/callback
twitchStreamerLogin: jaidchen
twitchBotLogin: jaidbot
videoRequestPriorityBase: 100
videoRequestPrioritySubs: 20
videoRequestPriorityVips: 20
videoRequestPriorityMods: 50
videoRequestPriorityBroadcaster: 100
videoSubscriptionPriority: 50
secondsBetweenYoutubeChecks: 5
twitchTickSeconds: 60
neutralTitles:
  - Moin, servus, moin!
  - Hi
githubAppId: 31980
githubWebhookPort: 31980
githubUser: Jaid
projectDependencyNames:
  express: Express
  koa: Koa
  webpack-config-jaid: Webpack
maxTechnologiesInTitle: 5
nicknames:
  flomey_: Flomey
